# Generated by Django 4.0.4 on 2022-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='alias',
            field=models.CharField(default='piss', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='macro',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
